/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Adapter AMS Port": {                            "en": "Adapter AMS Port",                                "de": "Adapter AMS Port",                                "ru": "Адаптер AMS Port",                                "pt": "Porta AMS do Adaptador",                          "nl": "Adapter AMS-poort",                               "fr": "Adaptateur AMS Port",                             "it": "Porta AMS dell'adattatore",                       "es": "Adaptador de puerto AMS",                         "pl": "Adapter portu AMC ",                              "zh-cn": "适配器AMS口"},
    "Adapter AMS-Net-ID": {                          "en": "Adapter AMS-Net-ID",                              "de": "Adapter AMS-Net-ID",                              "ru": "Адаптер AMS-Net-ID",                              "pt": "Adaptador AMS-Net-ID",                            "nl": "Adapter AMS-Net-ID",                              "fr": "Adaptateur AMS-Net-ID",                           "it": "Adattatore AMS-Net-ID",                           "es": "Adaptador AMS-Net-ID",                            "pl": "Adapter AMC-netto-kod",                           "zh-cn": "适配器AMS-Net-ID"},
    "In Seconds (min. 5 Sec)": {                     "en": "In Seconds (min. 5 Sec)",                         "de": "In Sekunden (min. 5 Sek)",                        "ru": "В секундах (мин. 5 сек)",                         "pt": "Em segundos (min. 5 seg.)",                       "nl": "In seconden (min. 5 sec.)",                       "fr": "En secondes (min. 5 sec)",                        "it": "In secondi (minimo 5 secondi)",                   "es": "En segundos (min. 5 seg.)",                       "pl": "W sekundach (min 5 s)",                           "zh-cn": "在几秒钟内(分钟。 5秒)"},
    "Interval for reconnect": {                      "en": "Interval for reconnect",                          "de": "Intervall für Verbindungsaufbau",                 "ru": "Интервал для переподключения",                    "pt": "Intervalo para reconectar",                       "nl": "Interval voor opnieuw verbinden",                 "fr": "Intervalle de reconnexion",                       "it": "Intervallo per la riconnessione",                 "es": "Intervalo de reconexión",                         "pl": "Czas na ponowne podłączenie",                     "zh-cn": "时间间隔为重新连接"},
    "On save Adapter restarts with new config immediately": {"en": "On save Adapter restarts with new config immediately", "de": "Nach dem Speichern startet der Adapter neu",      "ru": "При сохранении адаптер перезапускается с новым конфигом немедленно", "pt": "On save Adapter reinicia com nova configuração imediatamente", "nl": "Bij opslaan wordt Adapter onmiddellijk opnieuw opgestart met nieuwe config", "fr": "Lors de la sauvegarde, l’adaptateur redémarre immédiatement avec une nouvelle configuration.", "it": "On save Adapter si riavvia immediatamente con la nuova configurazione", "es": "Al guardar, el adaptador se reinicia con la nueva configuración inmediatamente.", "pl": "Zapisz ponownym uruchomieniu zasilacza z nowy konfig raz", "zh-cn": "在保存适配器重新启动与新的配置立即"},
    "Optional:": {                                   "en": "Optional:",                                       "de": "Optional:",                                       "ru": "Необязательный:",                                 "pt": "Opcional:",                                       "nl": "optioneel:",                                      "fr": "Optionnel:",                                      "it": "Opzionale:",                                      "es": "Opcional:",                                       "pl": "Dodatkowo:",                                      "zh-cn": "可选："},
    "PLC Runtime Version": {                         "en": "PLC Runtime Version",                             "de": "SPS Laufzeit Version",                            "ru": "Версия ПЛК",                                      "pt": "PLC Runtime Version",                             "nl": "PLC Runtime-versie",                              "fr": "Version d'exécution de l'automate",               "it": "Versione runtime PLC",                            "es": "Versión PLC Runtime",                             "pl": "PLC wersji środowiska wykonawczego",              "zh-cn": "PLC运行时版本"},
    "Target AMS-Net-ID": {                           "en": "Target AMS-Net-ID",                               "de": "Ziel AMS-Net-ID",                                 "ru": "Целевой AMS-Net-ID",                              "pt": "Target AMS-Net-ID",                               "nl": "Target AMS-Net-ID",                               "fr": "Identifiant AMS-Net cible",                       "it": "Target AMS-Net-ID",                               "es": "ID de AMS-Net de destino",                        "pl": "Celem AMC-netto-kod",                             "zh-cn": "目标AMS-Net-ID"},
    "Target IP-Adress": {                            "en": "Target IP-Adress",                                "de": "Ziel IP-Adresse",                                 "ru": "Целевой IP-адрес",                                "pt": "Target IP-Adress",                                "nl": "Target IP-adres",                                 "fr": "Adresse IP cible",                                "it": "Indirizzo IP target",                             "es": "Dirección IP de destino",                         "pl": "Docelowy adres IP",                               "zh-cn": "目标IP地址"},
    "Target Struct": {                               "en": "Target Struct",                                   "de": "Ziel Struktur",                                   "ru": "Целевая структура",                               "pt": "Estruturar Alvo",                                 "nl": "Doel structuur",                                  "fr": "Structure cible",                                 "it": "Target Struct",                                   "es": "Struct objetivo",                                 "pl": "Docelowa Struktura",                              "zh-cn": "目标结构"},
    "Target TCP Port": {                             "en": "Target TCP Port",                                 "de": "Ziel TCP Port",                                   "ru": "Целевой порт TCP",                                "pt": "Porta TCP de destino",                            "nl": "Target TCP-poort",                                "fr": "Port TCP cible",                                  "it": "Porta TCP target",                                "es": "Puerto TCP de destino",                           "pl": "Docelowy port TCP",                               "zh-cn": "目标TCP Port"},
    "Target variable table": {                       "en": "Target variable table",                           "de": "Ziel Variablentabelle",                           "ru": "Таблица целевых переменных",                      "pt": "Tabela de variáveis ​​de destino",                "nl": "Target variabele tabel",                          "fr": "Table de variables cible",                        "it": "Tabella delle variabili target",                  "es": "Tabla de variables de destino",                   "pl": "Docelowa zmienna stół",                           "zh-cn": "目标变量表"},
    "e.g. 192.168.0.1": {                            "en": "e.g. 192.168.0.1",                                "de": "z.B. 192.168.0.1",                                "ru": "например ",                                       "pt": "por exemplo. ",                                   "nl": "bijv. ",                                          "fr": "par exemple. ",                                   "it": "per esempio. ",                                   "es": "p.ej. ",                                          "pl": "na przykład, 192.168.0.1",                        "zh-cn": "例如为192.168.0.1"},
    "e.g. 192.168.0.1.1.1": {                        "en": "e.g. 192.168.0.1.1.1",                            "de": "z.B. 192.168.0.1.1.1",                            "ru": "например ",                                       "pt": "por exemplo. ",                                   "nl": "bijv. ",                                          "fr": "par exemple. ",                                   "it": "per esempio. ",                                   "es": "p.ej. ",                                          "pl": "na przykład, 192.168.0.1.1.1",                    "zh-cn": "例如192.168.0.1.1.1"},
    "e.g. 192.168.254.254.1.1": {                    "en": "e.g. 192.168.254.254.1.1",                        "de": "z.B. 192.168.254.254.1.1",                        "ru": "например ",                                       "pt": "por exemplo. ",                                   "nl": "bijv. ",                                          "fr": "par exemple. ",                                   "it": "per esempio. ",                                   "es": "p.ej. ",                                          "pl": "na przykład, 192.168.254.254.1.1",                "zh-cn": "例如192.168.254.254.1.1"},
    "e.g. 32905": {                                  "en": "e.g. 32905",                                      "de": "z.B. 32905",                                      "ru": "например ",                                       "pt": "por exemplo. ",                                   "nl": "bijv. ",                                          "fr": "par exemple. ",                                   "it": "per esempio. ",                                   "es": "p.ej. ",                                          "pl": "na przykład 32905",                               "zh-cn": "例如32905"},
    "e.g. ioBrokerHandshake": {                      "en": "e.g. ioBrokerHandshake",                          "de": "z.B. ioBrokerSchnittstelle",                      "ru": "например ",                                       "pt": "por exemplo. ",                                   "nl": "bijv. ",                                          "fr": "par exemple. ",                                   "it": "per esempio. ",                                   "es": "p.ej. ",                                          "pl": "na przykład, ioBrokerHandshake",                  "zh-cn": "例如ioBrokerHandshake"},
};